
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rpaudesbgayzicxwfhff.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJwYXVkZXNiZ2F5emljeHdmaGZmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM0NzIxMTgsImV4cCI6MjA1OTA0ODExOH0.joSGOWclzml_5UgvnejyDUFuM-NzG7_0cAYRwMWYipk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    storage: localStorage
  }
});
